logstash:
  image: logstash:1.5
  command: logstash -f /config/logstash.conf -v
  volumes:
    - "$PWD/config:/config:ro"
  ports:
    - "5005:5005"
    - "5005:5005/udp"
  links:
    - elasticsearch
elasticsearch:
  image: elasticsearch:1.5
  ports:
    - "9200:9200"
  # volumes:
    # Persist elasticsearch data
    # - "$PWD/esdata:/usr/share/elasticsearch/data"
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
