logstash:
  image: logstash:1.5
  command: logstash -f /config/logstash.conf -v
  volumes:
    - "$PWD/config:/config:ro"
  ports:
    - "3333:3333"
  links:
    - elasticsearch
elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
